version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:6.0-rc-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'website'
    build: .
    command: bash start_jobs.sh
    volumes:
      - '.:/nosso_amigo_secreto'
      - bundle_cache:/bundle_cache
    environment:
      - BUNDLE_PATH=/bundle_cache

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/nosso_amigo_secreto'
      - bundle_cache:/bundle_cache
    environment:
      - BUNDLE_PATH=/bundle_cache

  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  redis:
  postgres:
  bundle_cache:
